env:
  move_penalty: 0.02
  center_penalty_weight: 0.03
  bounce_reward: 1.0
  miss_penalty: 2.0
  perfect_hit_bonus: 1.0
  max_bounces: 100
  base_speed: 0.025
  speed_increment: 0.01
  speed_scale_every: 3
  paddle_speed: 0.03
  paddle_width: 80
  render_size: 400

train:
  episodes: 1000
  gamma: 0.997
  lr: 0.0005
  batch_size: 256
  memory_size: 500000
  epsilon_decay: 0.995
  min_epsilon: 0.05
  render_every: 500
  save_every: 500
  checkpoint_path: "checkpoints/model_ep1799.pth"
  load_model: true

test:
  model_path: "checkpoints/model_ep1799.pth"
  render: true
  episodes: 10
